let phone = [
    {
        id: 1,
        photo: "https://cdn.shopify.com/s/files/1/0015/2469/5117/products/iPhone-8-Black.png?v=1625059855",
        name: "iPhone 8",
        brand: "Apple",
        screen: "IPS de 4.7",
        frontcamera: "7MPX",
        internalmemory: "64GB",
        rammemory: "4ram",
        price: 250,
    },
    {
        id: 2,
        photo: "https://w7.pngwing.com/pngs/539/373/png-transparent-iphone-8-plus-iphone-7-plus-iphone-x-apple-telephone-apple-8plus-gadget-mobile-phone-magenta.png",
        name: "iPhone 8 plus",
        brand: "Apple",
        screen: "IPS de 5.5",
        frontcamera: "7MPX",
        internalmemory: "64GB",
        rammemory: "4ram",
        price: 300,
    },
    {
        id: 3,
        photo: "https://techgeekrd.com/wp-content/uploads/2020/07/iphone-se-white-select-2020.png",
        name: "iPhone SE",
        brand: "Apple",
        screen: "IPS de 4.7",
        frontcamera: "7MPX",
        internalmemory: "128GB",
        rammemory: "4ram",
        price: 320,
    },
    {
        id: 4,
        photo: "https://www.galichip.com/wp-content/uploads/2019/02/kisspng-telephone-apple-space-grey-64-gb-iphone-x-png-5b0b12d70b54b0.0221546515274523750464.jpg",
        name: "iPhone X",
        brand: "Apple",
        screen: "IPS de 5.8 ",
        frontcamera: "7MPX",
        internalmemory: "64GB",
        rammemory: "3ram",
        price: 330,
    },
    {
        id: 5,
        photo: "https://cbafederal.net/wp-content/uploads/2021/04/1080-iPhoneXR-Yellow-PB-PF-SCREEN-T.png",
        name: "iPhone XR",
        brand: "Apple",
        screen: "IPS de 6.1",
        frontcamera: "7MPX",
        internalmemory: "128GB",
        rammemory: "3ram",
        price: 380,
    },
    {
        id: 6,
        photo: "https://pngimg.com/d/iphone_11_PNG20.png",
        name: "iPhone 11",
        brand: "Apple",
        screen: "IPS de 6.1",
        frontcamera: "12MPX",
        internalmemory: "128GB",
        rammemory: "4ram",
        price: 480,
    },
    {
        id: 7,
        photo: "https://w7.pngwing.com/pngs/156/120/png-transparent-iphone11-pro-max.png",
        name: "iPhone 11 Pro Max",
        brand: "Apple",
        screen: "IPS de 6.5 ",
        frontcamera: "12MPX",
        internalmemory: "256GB",
        rammemory: "3ram",
        price: 650,
    },
    {
        id: 8,
        photo: "https://www.pngmart.com/files/15/Apple-iPhone-12-Transparent-Images-PNG.png",
        name: "iPhone 12",
        brand: "Apple",
        screen: "IPS de 6.1 ",
        frontcamera: "12MPX",
        internalmemory: "128GB",
        rammemory: "4ram",
        price: 630,
    },
    {
        id: 9,
        photo: "https://d2r9epyceweg5n.cloudfront.net/stores/001/054/848/products/graphite1-c83d0c3113ef63a94016541080261123-640-0.png",
        name: "iPhone 12 Pro",
        brand: "Apple",
        screen: "IPS de 6.7",
        frontcamera: "12MPX",
        internalmemory: "256GB",
        rammemory: "6ram",
        price: 680,
    },
    {
        id: 10,
        photo: "https://pngimg.com/uploads/iphone_13/iphone_13_PNG9.png",
        name: "iPhone 13 ",
        brand: "Apple",
        screen: "IPS de 6.1 ",
        frontcamera: "12MPX",
        internalmemory: "256GB",
        rammemory: "4ram",
        price: 940,
    },
    {
        id: 11,
        photo: "https://assets.stickpng.com/images/61d2f85b92b57c0004c64745.png",
        name: "iPhone 13 Pro Max",
        brand: "Apple",
        screen: "IPS de 6.7",
        frontcamera: "12MPX",
        internalmemory: "512GB",
        rammemory: "6ram",
        price: 1050,
    },
    {
        id: 12,
        photo: "https://w7.pngwing.com/pngs/378/624/png-transparent-iphone-14.png",
        name: "iPhone 14 Pro Max",
        brand: "Apple",
        screen: "IPS de 6.1",
        frontcamera: "12MPX",
        internalmemory: "512GB",
        rammemory: "6ram",
        price: 1330,
    },
    
]